modLoader = "javafml"
loaderVersion = "[50,)"
issueTrackerURL = "https://github.com/Vivecraft/VivecraftMod/issues"
license = "LGPLv3"

[[mods]]
modId = "vivecraft"
version = "${version}"
displayName = "Vivecraft"
displayURL = "https://modrinth.com/mod/vivecraft"
logoFile = "vivecraft_icon.png"
authors = "fayer3, Ferri_Arnus, IMS, jrbudda, minecraft player, Techjar"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
The VR mod for any loader!

Support us on Ko-Fi: https://ko-fi.com/vivecraft

Discord: https://discord.gg/jYyyv7zhSW
'''
updateJSONURL = "https://raw.githubusercontent.com/Vivecraft/VivecraftMod/forge-versions/forge_updates.json"

[[dependencies.vivecraft]]
modId = "forge"
mandatory = true
versionRange = "[50.0.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vivecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6]"
ordering = "NONE"
side = "BOTH"
