modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Vivecraft/VivecraftMod/issues"
license = "LGPLv3"

[[mods]]
modId = "vivecraft"
version = "${version}"
displayName = "Vivecraft"
displayURL = "https://modrinth.com/mod/vivecraft"
logoFile = "vivecraft_icon.png"
authors = "fayer3, Ferri_Arnus, IMS, jrbudda, minecraft player, Techjar"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
The VR mod for any loader!

Support us on Ko-Fi: https://ko-fi.com/vivecraft

Discord: https://discord.gg/jYyyv7zhSW
'''
updateJSONURL = "https://raw.githubusercontent.com/Vivecraft/VivecraftMod/forge-versions/neoforge_updates.json"

[[dependencies.vivecraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.21-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vivecraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "vivecraft.mixins.json"
[[mixins]]
config = "vivecraft.alexmobs.mixins.json"
[[mixins]]
config = "vivecraft.blur.mixins.json"
[[mixins]]
config = "vivecraft.bedrockify.mixins.json"
[[mixins]]
config = "vivecraft.cataclysm.mixins.json"
[[mixins]]
config = "vivecraft.dynamicfps.mixins.json"
[[mixins]]
config = "vivecraft.sodium.mixins.json"
[[mixins]]
config = "vivecraft.forge.sodium.mixins.json"
[[mixins]]
config = "vivecraft.iris.mixins.json"
[[mixins]]
config = "vivecraft.physicsmod.mixins.json"
[[mixins]]
config = "vivecraft.rei.mixins.json"
[[mixins]]
config = "vivecraft.resolutioncontrol.mixins.json"
[[mixins]]
config = "vivecraft.sereneseasons.mixins.json"
[[mixins]]
config = "vivecraft.optifine.mixins.json"
[[mixins]]
config = "vivecraft.neoforge.mixins.json"
